# Generated by Django 5.0.6 on 2024-06-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="is_available",
        ),
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                ],
                default="available",
                max_length=10,
            ),
        ),
    ]
