# Generated by Django 5.0.6 on 2024-06-12 05:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_reviews"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reviews",
            new_name="Review",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="property",
            new_name="listing",
        ),
    ]
