# Generated by Django 5.0.6 on 2024-06-12 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_reviews_review_rename_property_review_listing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="listing",
            new_name="property",
        ),
    ]
